# Generated by Django 3.1.7 on 2021-04-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='stop_time',
        ),
        migrations.AlterField(
            model_name='stop',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адреса'),
        ),
        migrations.CreateModel(
            name='ScheduledStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Час зупинки')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routes.stop')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduled_stops',
            field=models.ManyToManyField(to='routes.ScheduledStop'),
        ),
    ]
