# Generated by Django 3.2 on 2021-04-20 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер зміни')),
                ('start_time', models.TimeField(verbose_name='Початок зміни')),
                ('end_time', models.TimeField(verbose_name='Кінець зміни')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Кінець рейсу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Початок рейсу'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('scheduled', models.ManyToManyField(to='routes.Schedule')),
                ('shift_kind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routes.shiftkinds')),
            ],
        ),
    ]
