# Generated by Django 3.2 on 2021-04-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20210420_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='scheduled',
            new_name='schedules',
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
