# Generated by Django 3.1.7 on 2021-04-06 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transports', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('driver_license', models.CharField(blank=True, max_length=20, verbose_name='Посвідчення водія')),
                ('schedules', models.ManyToManyField(to='routes.Schedule')),
                ('transport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='transports.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
