# Generated by Django 3.1.7 on 2021-03-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trolleybus_car_number'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Driver'), (2, 'Admin'), (3, 'Director')], default=0, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='transport',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.trolleybus'),
        ),
    ]
