# Generated by Django 3.1.7 on 2021-04-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='transports.transport'),
        ),
    ]
