# Generated by Django 3.1.7 on 2021-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20210405_1102'),
        ('accounts', '0002_profile_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schedules',
            field=models.ManyToManyField(to='routes.Schedule'),
        ),
    ]
