# Generated by Django 3.1.7 on 2021-03-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210306_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='TrolleybusState',
        ),
    ]
