# Generated by Django 3.1.7 on 2021-03-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210306_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='time',
        ),
    ]
