# Generated by Django 3.1.7 on 2021-03-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210306_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolleybus',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.route'),
        ),
    ]
