# Generated by Django 3.2 on 2021-04-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transports.condition'),
        ),
    ]
