# Generated by Django 3.1.7 on 2021-04-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_auto_20210405_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Детальний опис')),
            ],
        ),
        migrations.RemoveField(
            model_name='transport',
            name='route_number',
        ),
    ]
