# Generated by Django 3.1.7 on 2021-04-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_auto_20210406_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Детальний опис'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transports.condition'),
        ),
    ]
