# Generated by Django 3.1.7 on 2021-04-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_auto_20210406_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='condition',
        ),
    ]
