# Generated by Django 3.1.7 on 2021-04-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0006_transport_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transports.condition'),
        ),
    ]
