# Generated by Django 3.1.7 on 2021-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0008_auto_20210406_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='condition',
            field=models.CharField(blank=True, default='ok', max_length=1000, verbose_name='Стан'),
        ),
    ]
